### ISSUE TITLE
Clicking dysfunctional in applications

### ISSUE THREAD

**Issue by luetage** [F-i-f/soft-brightness#10]
Whenever I lower the brightness with soft-brightness overlay, clicking in any application window won't work, no matter what the application. Gnome shell is still responsive on the other hand. Moreover mouse clicks are dysfunctional after suspend, no matter the brightness setting for the extension. It took me 2 days to realize that this extension is responsible, after uninstall all is fine again.

Fedora 31 Gnome 3.34.4

**Comment by F-i-f** [comment]
Thanks for your report.
Can you please tell me your Soft Brightness version and whether you're running an X11 or Wayland session?
If you could capture a system log when the problem happens, that'd be great.
To do that:
- Enable debug in the extensions preferences (Gnome Tweaks > Extensions > Soft Brigthness > [Gear Icon] > Debug > Toggle on).
- Turn the extension off in Gnome Tweaks.
- In Terminal, run `journalctl -f > output.log`
- Turn the extension on in Gnome Tweaks.
- Reproduce the problem (Lower brightness)
- Turn brightness back to 100%.
- Interrupt with Control-C the `journalctl` command.
- Attach `output.log` to this issue.

**Comment by luetage** [comment]
Yeah, I'm using Wayland, Soft-Brightness version 16.
[output.log](https://github.com/F-i-f/soft-brightness/files/4327499/output.log)

**Comment by F-i-f** [comment]
Thanks.
I can reproduce the problem.

Downgrading back to version 15 should fix the problem until I have time to address the underlying issue:
Download https://github.com/F-i-f/soft-brightness/releases/download/v15/soft-brightness@fifi.org.v15.shell-extension.zip and unzip the file under `~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/`.

**Comment by F-i-f** [comment]
Version 18 should fix the issue.
Until it's [reviewed](https://extensions.gnome.org/review/14525), you can download it from https://github.com/F-i-f/soft-brightness/releases/download/v18/soft-brightness@fifi.org.v18.shell-extension.zip and unzip the file under `~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/`.

**Comment by luetage** [comment]
Thank you for the fast fix, version 18 works. Mouse clicks are registered in applications after changing brightness and continue to work after waking from suspend.

**Comment by luetage** [comment]
Sorry to bother you, but I think there is still a small issue. While clicking works, the mouse cursor doesn't turn into a pointer anymore when brightness is lowered, at least I noticed this in one application so far, which is Vivaldi Snapshot 2.12.1849.7. Firefox doesn't seem affected. I'm not sure if this issue is connected and it certainly isn't bad, but maybe it has something to do with it. I also did a log again.

[output.log](https://github.com/F-i-f/soft-brightness/files/4330415/output.log)

**Comment by F-i-f** [comment]
Ok, I'm unsure about what you mean by the "mouse cursor not turning into a pointer"?  Can you try to rephrase or maybe send a screencast?
Since you're running Fedora 31, can you point me at which package you're using for Vivaldi Snapshot?  It doesn't show up in `dnf list`.
Note that there's long-standing bug in Gnome Shell where some cursor updates are not communicated properly to the shell (#5).
Can you try to reproduce the issue with the built-in zoom?
To do that:
- Temporarily disable all extensions: Tweaks > Extension > Click on the toggle in the title bar to off.
- Turn on the screen magnifier: Settings > Universal Access > Zoom > Turn On.
- Launch Vivaldi Snapshot
- Does the incorrect behavior manifests itself?
- Turn Zoom off.
- Turn extensions back on.

**Comment by luetage** [comment]
![Screencast from 13 03 2020 21_09_18](https://user-images.githubusercontent.com/13988217/76656814-b5db1d80-6570-11ea-9dd0-a92ae5b6cf3a.gif)
Here a screencast of the issue, I hope it works.

Vivaldi runs their own repository for rpm packages, see here: https://help.vivaldi.com/article/manual-setup-vivaldi-linux-repositories/

About the bug in gnome shell, it's similar, but as said this only happens when brightness is being lowered with soft-brightness. Nothing too annoying, it's just something I noticed in version 18.

I followed your steps with universal access zoom and there the mouse cursor doesn't change either when hovering over a link in Vivaldi.

**Comment by F-i-f** [comment]
Thanks for the details and the screencast: it's the pointer icon not updating when it should.
Since you have the same problem under Gnome's Zoom, this is a problem with Gnome-Shell and a duplicate of #5.
Feel free to report to Gnome-Shell's maintainers.  They won't care much it it's an extension breaking down, but they should be more responsive with a bug on a built-in feature (Zoom).

**Comment by luetage** [comment]
I understand, thank you for the explanation, will look into reporting this to gnome-shell.

**Comment by F-i-f** [comment]
If you do report a bug, please post a link here, or better, in #5.
Thanks!
