### ISSUE TITLE
Tiny cursor

### ISSUE THREAD

**Issue by mistamal** [F-i-f/soft-brightness#14]
Hi there. Thanks a lot for this great extension.

Just am having a small issue as the clones cursor is tiny. Its size won't change even if I try to make it bigger in the settings.

My question was simply how to disable the mouse cloning altogether? I don't mind working with a bright cursor. I saw some references to disabling the cloning in the extension.js file but am unsure which way would be cleanest.

Thanks in advance.

**Comment by F-i-f** [comment]
Hi,

I've been looking at disabling the mouse cloning as it's very often problematic (mouse lag).
I'm curious as to which setting you're using to make the cursor bigger?
Are you using _Settings_ > _Universal Access_ > _Cursor Size_ ?
I can reproduce the problem, I think that may be yet another Gnome Shell cursor tracking bug.
Can you try seeing if the problem happens with the Universal Access Zoom feature:

1. Remove / disable _Soft Brightness_.
2. Enable Zoom: _Settings_ > _Universal Access_ > _Zoom_ > _Enable_.
3. Enable bigger cursor size: _Settings_ > _Universal Access_ > _Cursor Size_

For me, once that's done, moving the cursor to the top menu bar (eg. System Menu) makes it shrink back to its normal size.

**Comment by mistamal** [comment]
I had in fact tried to increase the cursor size through the universal access submenu (didn't work initially). However, after enabling zoom with a magnification of 1x, the cursor size issue seems to be fixed.
In addition, I can confirm there is (slight)  lag in cursor movement; so an option to disable mouse tracking altogether would be beneficial.

Unrelated question: do you know if there would be a way to capture the brightness keys and implement dimming directly with xrandr? i have an OLED panel and although I can get something going with dbusproxy (by modifying the extension called OLED dimmer: /1222/oled-dimmer/), I can't stop the brightness keys or the slider from changing the intel_backlight brightness, which results in flashing between the xrandr reduced brightness and the full brightness (from intel_backlight i assume).

Thanks!

**Comment by F-i-f** [comment]
Okay.  I'll be releasing a new version shortly where you can disable the mouse cloning.

Regarding your unrelated questions:
1. It's dodgy to try to capture the brightness hotkeys, but gnome-settings-daemon really wants to grab them too, so you'll have to fight it (maybe disable the hotkeys in Gnome?).
2. I also have an OLED laptop, which is why I had to write this extension to get decent brightness control for it.  You could use xrandr, *but* the same xrandr settings are also controlled by gnome-settings-daemon to implement color profiles and night light.  So if you want to go this route, you'll have to disable the gnome-settings-daemon color management, which is not easy to do.  Fun fact, before I wrote the extension, that's how I controlled my OLED brightness.

**Comment by F-i-f** [comment]
Release 19 fixes the issue by adding a toggle for mouse cloning.
