### ISSUE TITLE
Long-term effects on the eyes

### ISSUE THREAD

**Issue by cristianlivella** [F-i-f/soft-brightness#28]
I've been using this extension for a few months now and I find it very convenient, thanks to @F-i-f  and the others dev who work on it!
I was just having a doubt, as far as my eyes and eye strain are concerned, is using this extension the same as actually lowering the screen brightness?
Instinctively I'd say no, however by setting the real screen brightness to maximum, and minimum with extension, it doesn't seem like the screen is emitting annoying light (I am using an IPS screen and an old LCD screen).
What do you think about it?
By using the computer for many hours a day, I would like to avoid over-straining my eyes. :sweat_smile:

**Comment by F-i-f** [comment]
The answer is it depends on the screen technology you're using.
- I won't get into CRTs since few of them are left.
- For LCDs (which work by having a bright light, the backlight, which is then colored and dimmed by the LCD layer in front of it), the real brightness controls the intensity of the backlight itself.
- For OLED screens, I haven't seen any hardware brightness control, and they always are rendering at full brightness, or are using some kind of software analogue very likely to work like Soft Brightness.

Using Soft Brightness will only change the color values of the displayed image by software (with an alpha channel overlay).
Soft brightness will degrade color rendering, while the real brightness control won't.  This is due to the limitation of having integer color representation.  The effect is particularly visible on gradients: as one lowers the Soft Brightness, the gradient is dithered with increasing banding error.
Soft brightness will typically allow extremely low brightness.  It can even go all the way down to 0% brightness if you override the default _Minimum brightness_ in its settings, while (typical, LCD) brightness controls are generally more limited in the lower range.
Soft Brightness will also allow finer-grained control.  I've seen LCD screens only have 8 different levels of brightness.  Soft Brightness can go up to 256 different levels (actually only limited by the display server (X/Wayland) pixel RGB representation).

I am not a doctor, and cannot recommend a real brightness control vs. soft brightness with regards to eye strain, but if you have to deal with very low brightness environment, Soft Brightness may be better as it allows for lower overall screen luminosity.  It may also be more comfortable than a hardware brightness setting as you can tune it very finely.
