### ISSUE TITLE
Mouse movement lags

### ISSUE THREAD

**Issue by ViBE-HU** [F-i-f/soft-brightness#30]
I'm on Ubuntu 20.04. I'm using a laptop with an external LG display via HDMI. Only the external active. Everything is updated and when I change the brightness the mouse starts to lag. Feels like the FPS drops down to 10-15.

**Comment by F-i-f** [comment]
Indeed, when the brightness is less than 100%, the mouse cursor can be laggy as it has to be redrawn by Gnome Shell with the correct alpha.  Unfortunately, there's not much I can do against that lag.

That's why you'll find in the extension's settings (Gnome Tweaks > Extensions > Soft Brightness) a toggle named _Mouse cursor brightness control_ that will remove the lag, but render the mouse cursor without the brightness correction applied.
