### ISSUE TITLE
Overlay covers workspace dock in overview

### ISSUE THREAD

**Issue by Tiamarth** [F-i-f/soft-brightness#4]
When brightness is turned down via Soft Brightness and thus the soft brightness overlay is enabled, I can't drag windows from one workspace to another in the overview. Functionality returns to normal when Soft Brightness is disabled.

Gnome 3.32
Soft Brightness 10

**Comment by F-i-f** [comment]
Thank you for this new report :-)
It's a regression caused by the code reorg needed to support brightness on the mouse cursor.
Try this update:
[soft-brightness@fifi.org-v11-1-ga0fb954.zip](https://github.com/F-i-f/soft-brightness/files/3110057/soft-brightness%40fifi.org-v11-1-ga0fb954.zip)
Download and unzip the file under `~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org` and overwrite the files that are in there.  Then restart gnome-shell.
It should be fixed.
Waiting for your confirmation before pushing yet-another-release.

**Comment by Tiamarth** [comment]
It does fix the issue, thanks again!

**Comment by F-i-f** [comment]
I've released the extension version 12 which fixes this last remaining issue with Drag-n-Drop.
It's currently under review by the gnome-shell team.
In meantime you can get it from the [project homepage](https://github.com/F-i-f/soft-brightness/) or download [version 12 directly here](https://github.com/F-i-f/soft-brightness/releases/download/v12/soft-brightness@fifi.org.v12.shell-extension.zip).

There is no change in the code between v11-1-ga0fb954 I've posted in comment 2 and this updated v12 version.

Thanks for the quick turn-around during testing.

**Comment by Tiamarth** [comment]
No worries. Soft Brightness saves my eyes quite a lot of strain. I honestly think it might be one of the only extensions I feel like I can't live without. So I'm happy to help. Even as minutely as this. Thank *you* for the quick fixes.
